### ISSUE TITLE
Doryphore 02/02/21 pas de webhook pour /edit ni creation d'une fiche

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki-extension-webhooks#10]
Doryphore 02/02/21 pas de webhook pour /edit ni creation d'une fiche

Doryphore : 02/02/21 
Extension webhooks : branche refacto adat 2 du 2/2/21

La création et la modification d'une fiche ne donnent pas de webhook sortant.
OK pour la suppression d'une fiche

**Comment by J9rem** [comment]
réparé par https://github.com/YesWiki/yeswiki/pull/709 normalement donc  je clos cette issue.

**Comment by srosset81** [comment]
Trop cool, merci !

**Comment by J9rem** [comment]
Par contre, @srosset81 si tu avais le temps de faire une mini review de https://github.com/YesWiki/yeswiki/pull/709 (Florian n'a pas trop le temps), ça me permettrait de déployer dans le coeur le correctif nécessaire.
(Vu que ça touche à l'ordre de parcours des actions et handlers, je veux bien m'assurer qu'il n'y a pas d'effet de bord, ..)
